services:
  bot:
    image: ghcr.io/${IMAGE_NAME}:latest
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DATABASE_URL: file:/app/data/db.sqlite
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
    volumes:
      - bot-data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
    driver: local